check50: 
  files: &check50_files
    - !exclude "*.pyc"
    - !exclude __pycache__
    - !require application.py
    - !require finance.db
    - !require helpers.py
    - !require requirements.txt

submit50: 
  files: *check50_files
